### ISSUE TITLE
スクリプトをなしで起動する

### ISSUE THREAD

**Issue by 5ee1e** [slime-hatena/launch-umamusume-from-steam#5]
SteamやWindowsのショートカットのリンク先を`dmmgameplayer://umamusume/cl/general`とすることで起動させることができる

これはDMM Game Player側から生成される`.url`のショートカットに記載されているため、おそらく最速かつネイティブ

管理者権限の通知は若干脆弱になる可能性があるが、`ユーザーアカウント制御設定の変更`を通知しないに変更することにより、対処できる

![unknown](https://user-images.githubusercontent.com/48326733/124623936-62a08300-deb7-11eb-9d2e-4f5b07b1cadd.png)

- [ ] 不明:Steamオーバーレイ　Steam側の設定に存在していないため?

**Comment by slime-hatena** [comment]
長期間放置してしまい申し訳ございません。
頂いた方法を試してみたところ、UACの制御が最低になっていれば「非Steamゲーム中」状態を維持できるようでした。
1段階でも設定が上がっていると、起動後にオンライン状態に戻ってしまうようです。

こちらのissueは追加情報としてREADMEの中からリンクさせていただこうかと思います。
ご報告ありがとうございました！
